name: Deploy to Contabo
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_USERNAME }}"
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}"

      - name: Build & Push Docker Image
        run: |
          docker build -t gjorgjibelkoski/workouts:latest -f backend/Dockerfile backend/
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker push gjorgjibelkoski/workouts:latest

      - name: Deploy to Contabo via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull gjorgjibelkoski/workouts:latest
            docker stop workouts-app || true
            docker rm workouts-app || true
            docker-compose up -d
