name: Deploy to Contabo
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish .NET App
        run: dotnet publish backend/backend.csproj -c Release -o ./publish

      - name: Build & Push Docker Image
        run: |
          docker build -t gjorgjibelkoski/workouts:latest .
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker push gjorgjibelkoski/workouts:latest

      - name: Deploy to Contabo via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull gjorgjibelkoski/workouts:latest
            docker stop workouts-app || true
            docker rm workouts-app || true
            docker-compose up -d
